Add Hugo
jcs/no_color pull request #185
Opened 2022-06-16 08:54 UTC by bep

2022-06-16 12:02 UTC, jcs requested changes

2022-06-16 12:02 UTC, jcs commented on index.md
> +|[Hugo](https://github.com/gohugoio/hugo) | Framework for building websites. | [v0.101.0](https://github.com/gohugoio/hugo/releases/tag/v0.101.0) |
Please remove trailing period

2022-06-20 19:19 UTC, jcs requested changes
You still didn't remove the period

2022-06-20 20:10 UTC, bep commented
Yea, right, my Norwegian head thought for a moment that "period" meant whitespace. Should be fixed now, sorry for the mixup.

2022-06-20 20:31 UTC, merged